# Generated by Django 5.2.17 on 2026-09-30 13:20

import django.db.models.deletion
from django.db import migrations, models

import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "Сотрудник", "verbose_name_plural": "Сотрудники"},
        ),
        migrations.AlterModelOptions(
            name="employeeskill",
            options={
                "verbose_name": "Навык сотрудника",
                "verbose_name_plural": "Навыки сотрудника",
            },
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"verbose_name": "Навык", "verbose_name_plural": "Навыки"},
        ),
        migrations.CreateModel(
            name="EmployeeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=employees.models.employee_image_upload_to,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Порядковый номер"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение сотрудника",
                "verbose_name_plural": "Изображения сотрудников",
                "ordering": ("order", "id"),
            },
        ),
    ]
