# Generated by Django 5.2.17 on 2026-09-30 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employees",
            "0002_alter_employee_options_alter_employeeskill_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeskill",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill_levels",
                to="employees.employee",
            ),
        ),
    ]
