# Generated by Django 5.2.17 on 2026-10-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_employee_hire_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="profession",
            field=models.CharField(
                blank=True,
                choices=[
                    ("QA", "Тестировщик"),
                    ("BE", "Бэкенд-разработчик"),
                    ("FE", "Фронтенд-разработчик"),
                ],
                max_length=2,
                verbose_name="Профессия",
            ),
        ),
    ]
