# Generated by Django 5.2.17 on 2026-09-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spots", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spot",
            options={"verbose_name": "Место", "verbose_name_plural": "Места"},
        ),
    ]
